name: Copy folder to other branch

on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy files to gh-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Fetch gh-pages branch and copy files
        env:
          SRC_FOLDER_PATH: './docs/dist'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git fetch                   
          git checkout $TARGET_BRANCH        
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "Deploy updated docs to gh-pages"

      - name: Push to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin gh-pages 
