name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Fetch and switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Remove index.html and assets/*
        run: |
          rm -f index.html 
          rm -rf assets/* 

      - name: Copy contents of docs/dist to root
        run: cp -r ../docs/dist/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy updated docs from main"
          git push origin gh-pages
